import { DeezerClient } from '../integrations/deezerClient.js';
import { SoundCloudClient } from '../integrations/soundcloudClient.js';
import { SpotifyClient } from '../integrations/spotifyClient.js';
import { YouTubeClient } from '../integrations/youtubeClient.js';
import { PlaylistRequest, PlaylistResult } from '../models/types.js';
import { getConnectedAccount } from './accountService.js';
import { parseVibe } from './aiParserService.js';
import { rankTracks } from './trackRankingService.js';
import { query } from '../db/client.js';

const clients = {
  spotify: new SpotifyClient(),
  youtube: new YouTubeClient(),
  soundcloud: new SoundCloudClient(),
  deezer: new DeezerClient()
};

export async function generatePlaylist(request: PlaylistRequest): Promise<PlaylistResult> {
  const account = await getConnectedAccount(request.userId, request.platform);
  if (!account) throw new Error(`No connected ${request.platform} account for user ${request.userId}`);

  const vibe = await parseVibe(request.vibeText);
  const targetTrackCount = Math.max(20, Math.min(40, request.targetTrackCount ?? 30));

  const client = clients[request.platform];
  const candidateTracks = await client.searchTracks(vibe, account, targetTrackCount * 2);
  const ranked = rankTracks(candidateTracks, vibe).slice(0, targetTrackCount);

  const playlistName = `${capitalize(vibe.mood)} ${capitalize(vibe.genre)} Vibez`;
  const playlistDescription = `Generated by Vibez from prompt: ${request.vibeText}`;

  const playlist = await client.createPlaylist(playlistName, playlistDescription, ranked, account);

  await persistPlaylist(request.userId, request.platform, playlist.id, playlistName, playlist.url, request.vibeText, ranked);

  return {
    playlistId: playlist.id,
    playlistName,
    playlistUrl: playlist.url,
    tracks: ranked
  };
}

export async function generatePlaylistVariants(request: PlaylistRequest): Promise<PlaylistResult[]> {
  const variants = [
    request.vibeText,
    `${request.vibeText} with deeper mood and atmosphere`,
    `${request.vibeText} with upbeat highlights and crowd favorites`
  ];

  const result: PlaylistResult[] = [];
  for (let i = 0; i < variants.length; i += 1) {
    result.push(
      await generatePlaylist({
        ...request,
        vibeText: variants[i]
      })
    );
  }

  return result;
}

async function persistPlaylist(
  userId: string,
  platform: string,
  playlistId: string,
  playlistName: string,
  playlistUrl: string,
  vibeText: string,
  tracks: PlaylistResult['tracks']
): Promise<void> {
  await query(
    `INSERT INTO playlists (user_id, platform, platform_playlist_id, name, url, vibe_text)
     VALUES ($1,$2,$3,$4,$5,$6)`,
    [userId, platform, playlistId, playlistName, playlistUrl, vibeText]
  );

  for (const track of tracks) {
    await query(
      `INSERT INTO tracks (platform_track_id, platform, title, artist, url, popularity, duration_ms, cover_art)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
       ON CONFLICT (platform_track_id, platform)
       DO UPDATE SET title = excluded.title, artist = excluded.artist, url = excluded.url, popularity = excluded.popularity, duration_ms = excluded.duration_ms, cover_art = excluded.cover_art`,
      [track.trackId, track.platform, track.title, track.artist, track.url, track.popularity, track.duration, track.coverArt ?? null]
    );
  }
}

function capitalize(input: string): string {
  if (!input.length) return input;
  return input[0].toUpperCase() + input.slice(1);
}
